### ISSUE TITLE
出现连接超时是什么原因呢？

### ISSUE THREAD

**Issue by kingideayou** [NetEase/pomelo-androidchat#2]
04-21 23:56:38.336    2126-2155/com.next.pomelodemo I/org.netease.pomelo﹕ connection is terminated.
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/org.netease.pomelo﹕ there is no listeners.
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ io.socket.SocketIOException: Error while handshaking
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at io.socket.IOConnection.handshake(IOConnection.java:322)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at io.socket.IOConnection.access$600(IOConnection.java:39)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ Caused by: java.net.SocketTimeoutException
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okio.Okio$2.read(Okio.java:113)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
04-21 23:56:38.336    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
04-21 23:56:38.337    2126-2155/com.next.pomelodemo W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
04-21 23:56:38.337    2126-2155/com.next.pomelodemo W/System.err﹕ at io.socket.IOConnection.handshake(IOConnection.java:313)
04-21 23:56:38.337    2126-2155/com.next.pomelodemo W/System.err﹕ ... 2 more
04-21 23:56:38.337    2126-2155/com.next.pomelodemo I/io.socket﹕ Cleanup

**Comment by kingideayou** [comment]
抱歉，是我的问题，自己已经解决了
